spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: pridesys.8428@gmail.com
    password: vzkv dplo kxwq vlbm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  application:
    name: auth-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/hospital_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:0000}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081

jwt:
  secret: my-super-secret-key-change-this-to-32bytes-min
  expiration: 900000
  refresh-expiration: 2592000000
